version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080

  localstack:
      image: localstack/localstack
      ports:
        - '4563-4599:4563-4599'
        - '8082:8081'
      environment:
        - SERVICES=s3
        - DATA_DIR=/tmp/localstack/data
        - DEBUG=1
      volumes:
        - "/tmp/localstack:/tmp/localstack"
        - ./.aws:/docker-entrypoint-initaws.d